# Generated by Django 5.1 on 2024-09-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
