# Generated by Django 5.1 on 2024-09-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buisness_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
