# Generated by Django 5.1 on 2024-09-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_buisness_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='buisness_name',
            new_name='business_name',
        ),
    ]
