# Generated by Django 5.1 on 2024-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_buisness_name_user_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
