# Generated by Django 5.1 on 2024-10-23 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0001_initial'),
        ('theater_managemant', '0023_alter_seat_column_alter_seat_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theater_managemant.screen'),
        ),
    ]
