# Generated by Django 5.1 on 2024-10-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0002_alter_showtime_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
