# Generated by Django 5.1 on 2024-10-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0003_alter_showtime_start_time'),
        ('theater_managemant', '0023_alter_seat_column_alter_seat_identifier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('screen', 'start_time')},
        ),
        migrations.DeleteModel(
            name='SeatBooking',
        ),
    ]
