# Generated by Django 5.1 on 2024-10-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0004_alter_showtime_unique_together_delete_seatbooking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together=set(),
        ),
    ]
