# Generated by Django 5.1 on 2024-10-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0006_movieschedule_dailyshow_seatbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
    ]
