# Generated by Django 5.1 on 2024-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0007_remove_showtime_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
