# Generated by Django 5.1 on 2024-10-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0008_alter_showtime_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieScheduleSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('time', models.TimeField()),
            ],
        ),
    ]
