# Generated by Django 5.1 on 2024-11-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0009_movieschedulesample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieScheduleSample',
        ),
    ]
