# Generated by Django 5.1 on 2024-11-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0010_delete_movieschedulesample'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
