# Generated by Django 5.1 on 2024-11-10 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0012_seatbooking_user'),
        ('theater_managemant', '0028_alter_snackitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='theater_managemant.seat'),
        ),
    ]
