# Generated by Django 5.1 on 2024-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0013_alter_seatbooking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
