# Generated by Django 5.1 on 2024-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0014_seatbooking_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='visitor',
            field=models.CharField(blank=True, default='anonymous_user', null=True),
        ),
    ]
