# Generated by Django 5.1 on 2024-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_management', '0015_seatbooking_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='visitor',
            field=models.CharField(blank=True, null=True),
        ),
    ]
