# Generated by Django 5.1 on 2024-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='theater',
            name='lng',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
