# Generated by Django 5.1 on 2024-10-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0002_alter_theater_lat_alter_theater_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
