# Generated by Django 5.1 on 2024-10-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0004_screen_tier_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='screen_photos/')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_images', to='theater_managemant.screen')),
            ],
        ),
    ]
