# Generated by Django 5.1 on 2024-10-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0005_screenimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='theater_managemant.screen'),
        ),
    ]
