# Generated by Django 5.1 on 2024-10-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0006_alter_tier_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='capacity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
