# Generated by Django 5.1 on 2024-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0008_sampleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenimage',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
