# Generated by Django 5.1 on 2024-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0009_screenimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
