# Generated by Django 5.1 on 2024-10-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0011_theater_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
