# Generated by Django 5.1 on 2024-10-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0014_remove_screenimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='photo',
        ),
        migrations.AddField(
            model_name='theater',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
