# Generated by Django 5.1 on 2024-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0015_remove_theater_photo_theater_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='theater_photos/'),
        ),
    ]
