# Generated by Django 5.1 on 2024-10-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0016_theater_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleImage',
        ),
    ]
