# Generated by Django 5.1 on 2024-10-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0021_remove_theater_total_screens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_layout',
        ),
        migrations.AddField(
            model_name='seat',
            name='column',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seat',
            name='identifier',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(default=' ', max_length=5),
        ),
        migrations.AddField(
            model_name='tier',
            name='columns',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='rows',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
