# Generated by Django 5.1 on 2024-10-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0022_remove_seat_seat_layout_seat_column_seat_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='column',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='identifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tier',
            name='columns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='rows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
