# Generated by Django 5.1 on 2024-11-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0023_alter_seat_column_alter_seat_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
