# Generated by Django 5.1 on 2024-11-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0025_snackcategory_snackitem_theatersnack'),
    ]

    operations = [
        migrations.AddField(
            model_name='snackitem',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
