# Generated by Django 5.1 on 2024-11-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0026_snackitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackitem',
            name='image_url',
            field=models.URLField(),
        ),
    ]
