# Generated by Django 5.1 on 2024-12-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_managemant', '0028_alter_snackitem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='geom',
        ),
    ]
